name: 'Hello World Docker Action'
run-name: 'Good Greetings ${{ inputs.who-to-greet}}'
description: 'Say hello!'

inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'world'
outputs:
  time:
    description: 'time'
    
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
