name: CI Docker
on:
  push:
    branches: 
      - main
    paths: 
      - hello-world-docker-action/**
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./hello-world-docker-action
        id: hello-action
        with:
          who-to-greet: '@pbfeigen_amadeus'

      - run: |
          echo "Time of execution: ${{ steps.hello-action.outputs.time }}"
